# Step 1: Use a base image with Python and scikit-learn
FROM python:3.12

# Step 2: Install additional dependencies (scikit-learn, SageMaker, and others if needed)
RUN pip install --upgrade pip
# Set GDAL_CONFIG environment variable for geospatial dependencies
ENV GDAL_CONFIG=/usr/bin/gdal-config
RUN pip install --no-cache-dir scikit-learn sagemaker pandas joblib flask gunicorn boto3

# Step 3: Set the working directory where your model and code will reside
WORKDIR /app/code

# Step 4: Copy the model and inference code into the container
# Assuming you have your model artifact in a .pkl format
COPY inference.py /opt/ml/code/inference.py
COPY models/mymodel.joblib /opt/ml/model/mymodel.joblib
COPY models/feature.joblib /opt/ml/model/feature.joblib

# Set environment variables for SageMaker
ENV PYTHONUNBUFFERED=TRUE
ENV SAGEMAKER_PROGRAM=inference.py

# Your custom inference code
# Step 5: Expose the port for API requests
EXPOSE 8080

# Step 6: Define the entry point command to run the inference script (for example with Flask)
ENTRYPOINT ["python", "-m", "gunicorn", "--bind", "0.0.0.0:8080", "--pythonpath", "/opt/ml/code/", "inference:app"]
